name: note_sound
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dev: ^1.0.0
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  hooks_riverpod: ^2.4.10
  intl: any
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.7
  expandable: ^5.0.1
  dart_scope_functions: ^0.1.4
  dart_melty_soundfont: ^1.1.11
  flutter_pcm_sound: ^1.2.0
  isar: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  build_verify: any
  custom_lint: ^0.6.2
  freezed: ^2.4.6
  go_router_builder: any
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  generate: true
  uses-material-design: true
